INVOICE_STATUS_DRAFT = "DRAFT"
INVOICE_STATUS_SENT = "SENT"
INVOICE_STATUS_PAID = "PAID"
INVOICE_STATUS_PARTIAL = "PARTIAL"
INVOICE_STATUS_OVERDUE = "OVERDUE"
INVOICE_STATUS_VOID = "VOID"

INVOICE_STATUSES = {
    INVOICE_STATUS_DRAFT,
    INVOICE_STATUS_SENT,
    INVOICE_STATUS_PAID,
    INVOICE_STATUS_PARTIAL,
    INVOICE_STATUS_OVERDUE,
    INVOICE_STATUS_VOID,
}

PAYMENT_STATUS_SUCCEEDED = "SUCCEEDED"
PAYMENT_STATUS_PENDING = "PENDING"
PAYMENT_STATUS_FAILED = "FAILED"

PAYMENT_STATUSES = {
    PAYMENT_STATUS_SUCCEEDED,
    PAYMENT_STATUS_PENDING,
    PAYMENT_STATUS_FAILED,
}

PAYMENT_METHOD_CASH = "cash"
PAYMENT_METHOD_ETRANSFER = "etransfer"
PAYMENT_METHOD_OTHER = "other"
PAYMENT_METHOD_CARD = "card"

PAYMENT_METHODS = {
    PAYMENT_METHOD_CASH,
    PAYMENT_METHOD_ETRANSFER,
    PAYMENT_METHOD_OTHER,
    PAYMENT_METHOD_CARD,
}


def normalize_status(value: str) -> str:
    normalized = value.upper()
    if normalized not in INVOICE_STATUSES:
        raise ValueError("Invalid invoice status")
    return normalized
